"""
Purpose: live audio -> transcription -> calendar tool call -> display frame.

This script keeps prior protocol contracts unchanged:
- Incoming audio packets: AUD0 framing from ESP32
- Outgoing image frame: IMG0 + raw RGB565 payload for LCD

Pipeline per utterance:
1) Receive AUD0 start/audio/end and write one WAV file.
2) On end, transcribe WAV with Whisper.
3) Send transcript to local Ollama with one native tool: add_calendar_event.
4) Update data/calendar.json.
5) Render current month calendar image (320x480).
6) Convert to RGB565 and send IMG0 frame back on same socket.

WARNING AI GENERATED CODE: This script was generated by an AI model and may contain errors or unsafe code. Please review and test thoroughly before using for any purpose.
"""

# pyright: reportMissingTypeStubs=false, reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnknownArgumentType=false

from __future__ import annotations

import calendar as calendar_module
from io import BytesIO
import json
import os
import re
import shutil
import socket
import struct
import time
import wave
import traceback
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.error import URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen

import imageio_ffmpeg
import ollama
import whisper
from PIL import Image, ImageDraw, ImageOps


ROOT = Path(__file__).resolve().parent
RECORDINGS_DIR = ROOT / "recordings"
DATA_DIR = ROOT / "data"
CALENDAR_PATH = DATA_DIR / "calendar.json"
TODO_PATH = DATA_DIR / "todo.txt"
SCREENSHOTS_DIR = ROOT / "screensavers"

OPENVERSE_IMAGE_SEARCH_URL = "https://api.openverse.org/v1/images/"

HOST = "0.0.0.0"
PORT = 5005

PACKET_MAGIC = b"AUD0"
PACKET_START = 1
PACKET_END = 2
PACKET_AUDIO = 3

IMAGE_MAGIC = b"IMG0"
DISPLAY_WIDTH = 320
DISPLAY_HEIGHT = 480

SAMPLE_RATE = 16000
CHANNELS = 1
SAMPLE_WIDTH = 2

WHISPER_MODEL_NAME = "base.en"
WHISPER_DEVICE = "cpu"
WHISPER_FP16 = False

OLLAMA_PRIMARY_MODEL = "hermes3:8b"
OLLAMA_FALLBACK_MODEL = "qwen3:8b"
TOOL_LOOP_MAX_TURNS = 4

RUN_START = time.monotonic()


def preview_text(value: Any, limit: int = 96) -> str:
    text = str(value).replace("\n", " ").strip()
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def log(stage: str, message: str = "", **fields: Any) -> None:
    elapsed = time.monotonic() - RUN_START
    parts = [f"[stage4 +{elapsed:7.2f}s]", stage]
    if message:
        parts.append(message)
    if fields:
        parts.extend(f"{key}={preview_text(value)}" for key, value in fields.items())
    print(" ".join(parts), flush=True)


@dataclass
class RecordingState:
    wav_file: wave.Wave_write | None = None
    path: Path | None = None
    started_at: float | None = None
    bytes_written: int = 0


def ensure_runtime_dirs() -> None:
    RECORDINGS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if not TODO_PATH.exists():
        TODO_PATH.write_text(json.dumps({"daily": [], "weekly": []}, indent=2), encoding="utf-8")
    SCREENSHOTS_DIR.mkdir(parents=True, exist_ok=True)


def ensure_ffmpeg_on_path() -> None:
    ffmpeg_exe = Path(imageio_ffmpeg.get_ffmpeg_exe())
    shim_dir = ROOT / ".cache" / "ffmpeg"
    shim_dir.mkdir(parents=True, exist_ok=True)
    shim_exe = shim_dir / "ffmpeg.exe"

    if not shim_exe.exists():
        shutil.copy2(ffmpeg_exe, shim_exe)

    path_entries = os.environ.get("PATH", "").split(os.pathsep)
    shim_dir_str = str(shim_dir)
    if shim_dir_str not in path_entries:
        os.environ["PATH"] = shim_dir_str + os.pathsep + os.environ.get("PATH", "")

    os.environ.setdefault("IMAGEIO_FFMPEG_EXE", str(shim_exe))


def recv_exact(sock: socket.socket, size: int) -> bytes:
    chunks = bytearray()
    while len(chunks) < size:
        chunk = sock.recv(size - len(chunks))
        if not chunk:
            raise EOFError("socket closed")
        chunks.extend(chunk)
    return bytes(chunks)


def read_aud0_packet(sock: socket.socket) -> tuple[int, bytes]:
    header = recv_exact(sock, 8)
    if header[:4] != PACKET_MAGIC:
        raise ValueError(f"bad packet magic: {header[:4]!r}")

    packet_type = header[4]
    payload_len = header[6] | (header[7] << 8)
    payload = recv_exact(sock, payload_len) if payload_len else b""
    return packet_type, payload


def new_recording_path() -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    return RECORDINGS_DIR / f"utterance_{timestamp}.wav"


def close_recording(state: RecordingState) -> Path | None:
    output_path = state.path
    if state.wav_file is not None:
        state.wav_file.close()

    if state.path and state.started_at is not None:
        duration = state.bytes_written / (SAMPLE_RATE * CHANNELS * SAMPLE_WIDTH)
        elapsed = time.monotonic() - state.started_at
        log("recording", "saved", file=state.path.name, duration=f"{duration:.2f}s", elapsed=f"{elapsed:.2f}s", bytes=state.bytes_written)

    state.wav_file = None
    state.path = None
    state.started_at = None
    state.bytes_written = 0
    return output_path


def start_recording(state: RecordingState) -> None:
    close_recording(state)
    state.path = new_recording_path()
    state.wav_file = wave.open(str(state.path), "wb")
    state.wav_file.setnchannels(CHANNELS)
    state.wav_file.setsampwidth(SAMPLE_WIDTH)
    state.wav_file.setframerate(SAMPLE_RATE)
    state.started_at = time.monotonic()
    state.bytes_written = 0
    log("recording", "start", file=state.path.name)


def append_audio(state: RecordingState, payload: bytes) -> None:
    if state.wav_file is None:
        return
    state.wav_file.writeframes(payload)
    state.bytes_written += len(payload)


def load_calendar() -> dict[str, Any]:
    if not CALENDAR_PATH.exists():
        return {"events": []}

    raw = CALENDAR_PATH.read_text(encoding="utf-8")
    data = json.loads(raw)
    if not isinstance(data, dict):
        return {"events": []}

    events = data.get("events")
    if not isinstance(events, list):
        return {"events": []}

    return {"events": events}


def save_calendar(data: dict[str, Any]) -> None:
    data.setdefault("events", [])
    CALENDAR_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    log("calendar", "saved", path=CALENDAR_PATH.name, event_count=len(data.get("events", [])))


def calendar_event_sort_key(event: dict[str, Any]) -> tuple[str, str, str]:
    return (
        str(event.get("date", "")),
        str(event.get("time", "")),
        str(event.get("title", "")),
    )


def validate_date_str(value: str) -> str:
    parsed = datetime.strptime(value, "%Y-%m-%d")
    return parsed.strftime("%Y-%m-%d")


def validate_time_str(value: str) -> str:
    parsed = datetime.strptime(value, "%H:%M")
    return parsed.strftime("%H:%M")


def normalize_recurrence(value: str | None) -> str:
    if value is None or value == "":
        return "none"

    normalized = value.strip().lower()
    if normalized in {"none", "yearly"}:
        return normalized

    raise ValueError("recurrence must be 'none' or 'yearly'")


def normalize_scope(value: str | None) -> str:
    if value is None or value == "":
        return "daily"
    normalized = value.strip().lower()
    if normalized in {"daily", "weekly"}:
        return normalized
    raise ValueError("scope must be 'daily' or 'weekly'")


def current_week_bounds(reference: date | None = None) -> tuple[date, date]:
    ref = reference or date.today()
    monday = ref - timedelta(days=ref.weekday())
    sunday = monday + timedelta(days=6)
    return monday, sunday


def load_todo_store() -> dict[str, Any]:
    if not TODO_PATH.exists():
        return {"daily": [], "weekly": []}

    try:
        raw = TODO_PATH.read_text(encoding="utf-8")
        data = json.loads(raw)
    except Exception:
        return {"daily": [], "weekly": []}

    if not isinstance(data, dict):
        return {"daily": [], "weekly": []}

    daily = data.get("daily")
    weekly = data.get("weekly")
    return {
        "daily": daily if isinstance(daily, list) else [],
        "weekly": weekly if isinstance(weekly, list) else [],
    }


def save_todo_store(data: dict[str, Any]) -> None:
    data.setdefault("daily", [])
    data.setdefault("weekly", [])
    TODO_PATH.write_text(json.dumps(data, indent=2), encoding="utf-8")
    log(
        "todo",
        "saved",
        path=TODO_PATH.name,
        daily_count=len(data.get("daily", [])),
        weekly_count=len(data.get("weekly", [])),
    )


def todo_item_id(scope: str) -> str:
    return f"{scope}-{datetime.now().strftime('%Y%m%d_%H%M%S_%f')}"


def normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip().lower())


def todo_item_sort_key(item: dict[str, Any]) -> tuple[str, str]:
    return (str(item.get("created_at", "")), str(item.get("id", "")))


def calendar_events_for_todo_scope(scope: str) -> list[dict[str, Any]]:
    events = load_calendar().get("events", [])
    if not isinstance(events, list):
        return []

    today = date.today()
    monday, sunday = current_week_bounds(today)
    output: list[dict[str, Any]] = []

    for event in events:
        if not isinstance(event, dict):
            continue

        try:
            event_date = datetime.strptime(str(event.get("date", "")).strip(), "%Y-%m-%d").date()
        except Exception:
            continue

        if scope == "daily" and event_date == today:
            output.append(dict(event))
        elif scope == "weekly" and monday <= event_date <= sunday:
            output.append(dict(event))
        elif scope == "all" and (event_date == today or monday <= event_date <= sunday):
            output.append(dict(event))

    return output


def reconcile_todos_with_calendar(todo_items: list[dict[str, Any]], calendar_events: list[dict[str, Any]]) -> dict[str, Any]:
    matched_todo_ids: set[str] = set()
    matched_calendar_indexes: set[int] = set()

    for todo_item in todo_items:
        todo_text = normalize_text(str(todo_item.get("text", "")))
        if not todo_text:
            continue

        for calendar_index, event in enumerate(calendar_events):
            if calendar_index in matched_calendar_indexes:
                continue

            title = normalize_text(str(event.get("title", "")))
            notes = normalize_text(str(event.get("notes", "")))
            if todo_text in title or title in todo_text or (notes and todo_text in notes):
                matched_todo_ids.add(str(todo_item.get("id", "")))
                matched_calendar_indexes.add(calendar_index)
                break

    todo_ids = {str(item.get("id", "")) for item in todo_items}
    matched_calendar_titles = {str(calendar_events[index].get("title", "")) for index in matched_calendar_indexes}

    return {
        "matched_todos": [item for item in todo_items if str(item.get("id", "")) in matched_todo_ids],
        "unmatched_todos": [item for item in todo_items if str(item.get("id", "")) not in matched_todo_ids],
        "matched_calendar_events": [calendar_events[index] for index in sorted(matched_calendar_indexes)],
        "unmatched_calendar_events": [event for index, event in enumerate(calendar_events) if index not in matched_calendar_indexes],
        "matched_calendar_titles": sorted(matched_calendar_titles),
        "todo_ids": sorted(todo_ids),
    }


def tool_add_todo_item(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        text = str(arguments.get("text", "")).strip()
        scope = normalize_scope(arguments.get("scope"))

        if not text:
            raise ValueError("text is required")

        now = datetime.now()
        item: dict[str, Any] = {
            "id": todo_item_id(scope),
            "scope": scope,
            "text": text,
            "done": False,
            "created_at": now.isoformat(timespec="seconds"),
            "completed_at": None,
        }

        if scope == "daily":
            item["date"] = now.strftime("%Y-%m-%d")
        else:
            week_start, week_end = current_week_bounds(now.date())
            item["week_start"] = week_start.strftime("%Y-%m-%d")
            item["week_end"] = week_end.strftime("%Y-%m-%d")

        todo_data = load_todo_store()
        todo_key = "daily" if scope == "daily" else "weekly"
        todo_data[todo_key].append(item)
        todo_data[todo_key].sort(key=todo_item_sort_key)
        save_todo_store(todo_data)
        log("todo", "item added", scope=scope, id=item["id"], text=text)
        return {"ok": True, "item": item, "count": len(todo_data[todo_key])}
    except Exception as exc:
        log("todo", "add failed", error=exc)
        return {"ok": False, "error": str(exc)}


def tool_complete_todo_item(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        scope = arguments.get("scope")
        item_id = str(arguments.get("id", "")).strip()
        text = str(arguments.get("text", "")).strip()

        if not item_id and not text:
            raise ValueError("id or text is required")

        todo_data = load_todo_store()
        scopes = [normalize_scope(scope)] if scope else ["daily", "weekly"]
        now = datetime.now().isoformat(timespec="seconds")
        matched: list[dict[str, Any]] = []

        for todo_key in scopes:
            items = todo_data.get(todo_key, [])
            if not isinstance(items, list):
                continue

            for item in items:
                if not isinstance(item, dict):
                    continue

                matches = False
                if item_id and str(item.get("id", "")).strip() == item_id:
                    matches = True
                elif text and normalize_text(text) in normalize_text(str(item.get("text", ""))):
                    matches = True

                if matches and not item.get("done", False):
                    item["done"] = True
                    item["completed_at"] = now
                    matched.append(dict(item))

        if not matched:
            return {"ok": False, "error": "no matching todo item found"}

        save_todo_store(todo_data)
        log("todo", "item completed", match_count=len(matched), id=item_id or "(text)", text=text or "(none)")
        return {"ok": True, "matched": matched, "match_count": len(matched)}
    except Exception as exc:
        log("todo", "complete failed", error=exc)
        return {"ok": False, "error": str(exc)}


def tool_lookup_todo_items(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        scope_raw = str(arguments.get("scope", "")).strip().lower()
        if scope_raw in {"daily", "weekly", "all"}:
            scope = scope_raw
        else:
            scope = "all"
        query = str(arguments.get("query", "")).strip().lower()
        done_filter = arguments.get("done")

        todo_data = load_todo_store()
        if scope == "daily":
            items = [item for item in todo_data.get("daily", []) if isinstance(item, dict) and item.get("date") == date.today().strftime("%Y-%m-%d")]
        elif scope == "weekly":
            week_start, _week_end = current_week_bounds()
            items = [item for item in todo_data.get("weekly", []) if isinstance(item, dict) and item.get("week_start") == week_start.strftime("%Y-%m-%d")]
        else:
            items = [item for bucket in (todo_data.get("daily", []), todo_data.get("weekly", [])) for item in bucket if isinstance(item, dict)]

        filtered_items: list[dict[str, Any]] = []
        for item in items:
            if query and query not in normalize_text(str(item.get("text", ""))):
                continue
            if done_filter is not None and bool(item.get("done", False)) != bool(done_filter):
                continue
            filtered_items.append(dict(item))

        calendar_events = calendar_events_for_todo_scope(scope)
        reconciliation = reconcile_todos_with_calendar(filtered_items, calendar_events)

        log(
            "todo",
            "lookup",
            scope=scope,
            query=query or "(none)",
            done=done_filter if done_filter is not None else "any",
            item_count=len(filtered_items),
            calendar_count=len(calendar_events),
        )
        return {
            "ok": True,
            "scope": scope,
            "items": filtered_items,
            "calendar_events": calendar_events,
            "reconciliation": reconciliation,
            "item_count": len(filtered_items),
            "calendar_count": len(calendar_events),
        }
    except Exception as exc:
        log("todo", "lookup failed", error=exc)
        return {"ok": False, "error": str(exc)}


def tool_add_calendar_event(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        title = str(arguments.get("title", "")).strip()
        date_str = str(arguments.get("date", "")).strip()
        time_str = str(arguments.get("time", "")).strip()
        notes = str(arguments.get("notes", "")).strip()
        recurrence = normalize_recurrence(arguments.get("recurrence"))

        if not title:
            raise ValueError("title is required")
        if not date_str:
            raise ValueError("date is required in YYYY-MM-DD")
        if not time_str:
            raise ValueError("time is required in HH:MM")

        normalized_date = validate_date_str(date_str)
        normalized_time = validate_time_str(time_str)

        calendar_data = load_calendar()
        event = {
            "title": title,
            "date": normalized_date,
            "time": normalized_time,
            "recurrence": recurrence,
        }
        if notes:
            event["notes"] = notes

        calendar_data["events"].append(event)
        calendar_data["events"].sort(key=calendar_event_sort_key)
        save_calendar(calendar_data)
        log("calendar", "event added", title=title, date=normalized_date, time=normalized_time, recurrence=recurrence, event_count=len(calendar_data["events"]))

        return {"ok": True, "event": event, "event_count": len(calendar_data["events"])}
    except Exception as exc:
        log("calendar", "event add failed", error=exc)
        return {"ok": False, "error": str(exc)}


def tool_remove_calendar_event(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        title = str(arguments.get("title", "")).strip()
        date_str = str(arguments.get("date", "")).strip()
        time_str = str(arguments.get("time", "")).strip()
        recurrence = str(arguments.get("recurrence", "")).strip().lower()
        query = str(arguments.get("query", "")).strip().lower()
        notes_contains = str(arguments.get("notes_contains", "")).strip().lower()

        if date_str:
            date_str = validate_date_str(date_str)
        if time_str:
            time_str = validate_time_str(time_str)
        if recurrence and recurrence not in {"none", "yearly"}:
            raise ValueError("recurrence must be 'none' or 'yearly'")

        if not any([title, date_str, time_str, recurrence, query, notes_contains]):
            raise ValueError("one or more selection criteria are required")

        calendar_data = load_calendar()
        events = calendar_data.get("events", [])
        if not isinstance(events, list):
            events = []

        removed_events: list[dict[str, Any]] = []
        kept_events: list[dict[str, Any]] = []

        for event in events:
            if not isinstance(event, dict):
                kept_events.append(event)
                continue

            event_title = str(event.get("title", "")).strip()
            event_date = str(event.get("date", "")).strip()
            event_time = str(event.get("time", "")).strip()
            event_recurrence = str(event.get("recurrence", "none")).strip().lower()
            event_notes = str(event.get("notes", "")).strip().lower()

            searchable_text = " ".join([event_title, event_date, event_time, event_recurrence, event_notes]).lower()

            matches = True
            if title:
                matches = matches and normalize_text(title) == normalize_text(event_title)
            if matches and date_str:
                matches = event_date == date_str
            if matches and time_str:
                matches = event_time == time_str
            if matches and recurrence:
                matches = event_recurrence == recurrence
            if matches and query:
                matches = query in searchable_text
            if matches and notes_contains:
                matches = notes_contains in event_notes

            if matches:
                removed_events.append(event)
            else:
                kept_events.append(event)

        if not removed_events:
            return {"ok": False, "error": "no matching event found"}

        calendar_data["events"] = kept_events
        save_calendar(calendar_data)
        log(
            "calendar",
            "event removed",
            title=title or "(criteria)",
            date=date_str or "any",
            time=time_str or "any",
            recurrence=recurrence or "any",
            query=query or "(none)",
            notes=notes_contains or "(none)",
            removed_count=len(removed_events),
            event_count=len(kept_events),
        )

        return {"ok": True, "removed": removed_events, "event_count": len(kept_events), "removed_count": len(removed_events)}
    except Exception as exc:
        log("calendar", "event remove failed", error=exc)
        return {"ok": False, "error": str(exc)}


def tool_lookup_calendar_events(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        query = str(arguments.get("query", "")).strip().lower()
        title = str(arguments.get("title", "")).strip().lower()
        date_str = str(arguments.get("date", "")).strip()
        time_str = str(arguments.get("time", "")).strip()
        recurrence = str(arguments.get("recurrence", "")).strip().lower()
        notes_contains = str(arguments.get("notes_contains", "")).strip().lower()
        limit_raw = arguments.get("limit", 0)

        if date_str:
            date_str = validate_date_str(date_str)
        if time_str:
            time_str = validate_time_str(time_str)
        if recurrence and recurrence not in {"none", "yearly"}:
            raise ValueError("recurrence must be 'none' or 'yearly'")

        try:
            limit = int(limit_raw)
        except Exception:
            limit = 0

        calendar_data = load_calendar()
        events = calendar_data.get("events", [])
        if not isinstance(events, list):
            events = []

        if not any([query, title, date_str, time_str, recurrence, notes_contains]):
            log("calendar", "lookup", mode="all-events", match_count=len(events))
            return {"ok": True, "mode": "all-events", "matches": [dict(event) for event in events if isinstance(event, dict)], "match_count": len(events)}

        matches: list[dict[str, Any]] = []
        for event in events:
            if not isinstance(event, dict):
                continue

            event_title = str(event.get("title", "")).strip()
            event_date = str(event.get("date", "")).strip()
            event_time = str(event.get("time", "")).strip()
            event_recurrence = str(event.get("recurrence", "none")).strip().lower()
            event_notes = str(event.get("notes", "")).strip()

            searchable_text = " ".join([event_title, event_date, event_time, event_recurrence, event_notes]).lower()

            if query and query not in searchable_text:
                continue
            if title and title not in event_title.lower():
                continue
            if date_str and event_date != date_str:
                continue
            if time_str and event_time != time_str:
                continue
            if recurrence and event_recurrence != recurrence:
                continue
            if notes_contains and notes_contains not in event_notes.lower():
                continue

            matches.append(dict(event))
            if limit > 0 and len(matches) >= limit:
                break

        log(
            "calendar",
            "lookup",
            mode="filtered",
            query=query or "(none)",
            title=title or "(none)",
            date=date_str or "any",
            time=time_str or "any",
            recurrence=recurrence or "any",
            notes=notes_contains or "(none)",
            match_count=len(matches),
        )
        return {"ok": True, "mode": "filtered", "matches": matches, "match_count": len(matches)}
    except Exception as exc:
        log("calendar", "lookup failed", error=exc)
        return {"ok": False, "error": str(exc)}


def sanitize_filename_component(value: str, fallback: str = "image") -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", value.strip())
    cleaned = cleaned.strip("._-")
    return cleaned[:80] if cleaned else fallback


def fetch_url_bytes(url: str, timeout_seconds: int = 20) -> bytes:
    request = Request(url, headers={"User-Agent": "Mozilla/5.0 Stage4CalendarPipeline/1.0"})
    with urlopen(request, timeout=timeout_seconds) as response:
        return response.read()


def search_openverse_images(query: str, limit: int) -> list[dict[str, Any]]:
    page_size = max(1, min(limit, 20))
    params = urlencode({"q": query, "page_size": page_size})
    search_url = f"{OPENVERSE_IMAGE_SEARCH_URL}?{params}"
    request = Request(search_url, headers={"User-Agent": "Mozilla/5.0 Stage4CalendarPipeline/1.0"})

    with urlopen(request, timeout=20) as response:
        payload = response.read().decode("utf-8", errors="replace")

    data = json.loads(payload)
    results = data.get("results") or []
    output: list[dict[str, Any]] = []
    for result in results:
        if isinstance(result, dict):
            output.append(result)
    return output


def tool_lookup_save_image(arguments: dict[str, Any]) -> dict[str, Any]:
    try:
        query = str(arguments.get("query", "")).strip()
        title = str(arguments.get("title", "")).strip()
        creator = str(arguments.get("creator", "")).strip()
        license_name = str(arguments.get("license", "")).strip().lower()
        source = str(arguments.get("source", "openverse")).strip().lower() or "openverse"

        try:
            limit = int(arguments.get("limit", 5))
        except Exception:
            limit = 5
        limit = max(1, min(limit, 20))

        try:
            selected_index = int(arguments.get("index", 0))
        except Exception:
            selected_index = 0

        if source != "openverse":
            raise ValueError("only the openverse source is supported right now")

        search_terms = query or title or creator
        if not search_terms:
            raise ValueError("query, title, or creator is required")

        log("images", "search start", query=search_terms, source=source, limit=limit)

        results = search_openverse_images(search_terms, limit)
        matches: list[dict[str, Any]] = []

        for result in results:
            result_title = str(result.get("title", "")).strip()
            result_creator = str(result.get("creator", "")).strip()
            result_license = str(result.get("license", "")).strip().lower()

            if title and title.lower() not in result_title.lower():
                continue
            if creator and creator.lower() not in result_creator.lower():
                continue
            if license_name and license_name not in result_license:
                continue

            matches.append(result)

        if not matches:
            return {"ok": False, "error": "no matching images found"}

        selected_index = max(0, min(selected_index, len(matches) - 1))
        selected = matches[selected_index]
        image_url = str(
            selected.get("thumbnail")
            or selected.get("thumbnail_url")
            or selected.get("url")
            or ""
        ).strip()
        if not image_url:
            raise ValueError("selected result did not include an image url")

        image_bytes = fetch_url_bytes(image_url)
        with Image.open(BytesIO(image_bytes)) as downloaded:
            image = downloaded.convert("RGB")

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        saved_name = sanitize_filename_component(str(selected.get("title") or search_terms))
        saved_path = SCREENSHOTS_DIR / f"{saved_name}_{timestamp}.png"
        image.save(saved_path, format="PNG")

        metadata = {
            "query": query,
            "title": str(selected.get("title", "")),
            "creator": str(selected.get("creator", "")),
            "license": str(selected.get("license", "")),
            "source": source,
            "image_url": image_url,
            "page_url": str(selected.get("foreign_landing_url", "")),
            "saved_path": str(saved_path),
        }
        saved_path.with_suffix(".json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

        log(
            "images",
            "saved",
            title=metadata["title"] or "(untitled)",
            creator=metadata["creator"] or "(unknown)",
            license=metadata["license"] or "(unknown)",
            path=saved_path.name,
            source_url=image_url,
        )

        return {"ok": True, "saved_path": str(saved_path), "metadata": metadata, "match_count": len(matches)}
    except (URLError, TimeoutError, OSError, json.JSONDecodeError, ValueError) as exc:
        log("images", "save failed", error=exc)
        return {"ok": False, "error": str(exc)}


def load_image_for_display(image_path: Path) -> Image.Image:
    with Image.open(image_path) as loaded:
        return loaded.convert("RGB")


def newest_calendar_event_date() -> date | None:
    calendar_data = load_calendar()
    events = calendar_data.get("events", [])
    latest_date: date | None = None

    for event in events:
        if not isinstance(event, dict):
            continue
        date_text = str(event.get("date", "")).strip()
        try:
            event_date = datetime.strptime(date_text, "%Y-%m-%d").date()
        except Exception:
            continue

        if latest_date is None or event_date > latest_date:
            latest_date = event_date

    return latest_date


def newest_event_after_removal() -> date | None:
    return newest_calendar_event_date()


def message_to_dict(message_obj: Any) -> dict[str, Any]:
    if isinstance(message_obj, dict):
        return message_obj

    if hasattr(message_obj, "model_dump"):
        dumped = message_obj.model_dump(exclude_none=True)
        if isinstance(dumped, dict):
            return dumped

    return {
        "role": "assistant",
        "content": getattr(message_obj, "content", "") or "",
        "tool_calls": getattr(message_obj, "tool_calls", None),
    }


def extract_tool_calls(message_dict: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    calls = []
    raw_calls = message_dict.get("tool_calls") or []

    for call in raw_calls:
        if isinstance(call, dict):
            function_part = call.get("function") or {}
            name = function_part.get("name")
            arguments = function_part.get("arguments") or {}
        else:
            function_part = getattr(call, "function", None)
            name = getattr(function_part, "name", None)
            arguments = getattr(function_part, "arguments", {}) if function_part else {}

        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except json.JSONDecodeError:
                arguments = {}

        if not isinstance(arguments, dict):
            arguments = {}

        if isinstance(name, str) and name:
            calls.append((name, arguments))

    return calls


def available_model_names() -> set[str]:
    try:
        response = ollama.list()
    except Exception:
        return set()

    data = response if isinstance(response, dict) else response.model_dump(exclude_none=True)
    models = data.get("models") or []
    names: set[str] = set()
    for model_entry in models:
        if isinstance(model_entry, dict):
            name = model_entry.get("model") or model_entry.get("name")
            if isinstance(name, str):
                names.add(name)
    return names


def ensure_ollama_model() -> str:
    names = available_model_names()
    if OLLAMA_PRIMARY_MODEL in names:
        return OLLAMA_PRIMARY_MODEL
    if OLLAMA_FALLBACK_MODEL in names:
        return OLLAMA_FALLBACK_MODEL

    log("ollama", "pulling primary model", model=OLLAMA_PRIMARY_MODEL)
    ollama.pull(OLLAMA_PRIMARY_MODEL)
    return OLLAMA_PRIMARY_MODEL


def run_tool_call_loop(transcript: str, model_name: str) -> tuple[str, bool, date | None, Path | None]:
    today_str = date.today().strftime("%Y-%m-%d")
    current_month_name = datetime.now().strftime("%B")
    current_year_str = datetime.now().strftime("%Y")
    system_prompt = (
        "You are a calendar assistant using tool calling. "
        "When adding events, always call add_calendar_event with date in YYYY-MM-DD and time in HH:MM (24h). "
        f"Today is {today_str}. The current month is {current_month_name} {current_year_str}. "
        "Never assume the year is 2022 unless the user explicitly says so. "
        "For weekday phrases like Friday at 2pm, resolve to the next upcoming weekday from today. "
        "Use recurrence='yearly' only when user asks yearly recurrence; otherwise recurrence='none'. "
        "If you need to inspect stored calendar entries or you are missing identifying details, call lookup_calendar_events first. "
        "lookup_calendar_events returns full stored event records, including title, date, time, recurrence, and notes, so you can use those fields for bulk deletes. "
        "For requests like deleting all non-recurring events, you may call lookup_calendar_events to inspect them and then call remove_calendar_event with criteria such as recurrence='none', date, time, query, or notes_contains instead of naming every event individually. "
        "If a delete request can be answered by a single criterion, prefer a criteria-based remove call rather than deleting one event at a time. "
        "If the user asks for an image or screensaver, call lookup_save_image and only use open-licensed or public-domain image sources. "
        "If user intent is to remove an event, call remove_calendar_event. "
        "If the user asks to add, complete, or view tasks, use add_todo_item, complete_todo_item, and lookup_todo_items. "
        "If user intent is not to add, remove, inspect, or save an image, do not call tools and explain briefly."
    )

    tool_schemas = [
        {
            "type": "function",
            "function": {
                "name": "add_calendar_event",
                "description": "Add an event to the local calendar store.",
                "parameters": {
                    "type": "object",
                    "required": ["title", "date", "time", "recurrence"],
                    "properties": {
                        "title": {"type": "string", "description": "Short event title"},
                        "date": {"type": "string", "description": "Event date in YYYY-MM-DD"},
                        "time": {"type": "string", "description": "Event time in HH:MM 24-hour format"},
                        "recurrence": {
                            "type": "string",
                            "description": "Use 'none' or 'yearly'",
                            "enum": ["none", "yearly"],
                        },
                        "notes": {"type": "string", "description": "Optional notes"},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "remove_calendar_event",
                "description": "Remove one or more matching events from the local calendar store. You can use title, date, time, recurrence, notes_contains, or query to delete by criteria instead of naming every event.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string", "description": "Event title to remove"},
                        "date": {"type": "string", "description": "Optional event date in YYYY-MM-DD"},
                        "time": {"type": "string", "description": "Optional event time in HH:MM 24-hour format"},
                        "recurrence": {
                            "type": "string",
                            "description": "Optional recurrence filter",
                            "enum": ["none", "yearly"],
                        },
                        "query": {"type": "string", "description": "Optional free-text match across stored event fields"},
                        "notes_contains": {"type": "string", "description": "Optional note substring filter"},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "lookup_calendar_events",
                "description": "Inspect the local calendar store and return any matching events, or the full event list when no identifying criteria are provided.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Free-text search across all stored event fields"},
                        "title": {"type": "string", "description": "Optional title substring to match"},
                        "date": {"type": "string", "description": "Optional event date in YYYY-MM-DD"},
                        "time": {"type": "string", "description": "Optional event time in HH:MM 24-hour format"},
                        "recurrence": {
                            "type": "string",
                            "description": "Optional recurrence filter",
                            "enum": ["none", "yearly"],
                        },
                        "notes_contains": {"type": "string", "description": "Optional substring filter for notes"},
                        "limit": {"type": "integer", "description": "Optional maximum number of matches to return when filtering", "minimum": 1, "maximum": 100},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "lookup_save_image",
                "description": "Search Openverse for a reusable image, save it locally, and return its metadata for screensaver use.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string", "description": "Search phrase for the image"},
                        "title": {"type": "string", "description": "Optional title substring filter"},
                        "creator": {"type": "string", "description": "Optional creator substring filter"},
                        "license": {"type": "string", "description": "Optional license substring filter"},
                        "source": {"type": "string", "description": "Image source to search", "enum": ["openverse"]},
                        "limit": {"type": "integer", "description": "Maximum number of search results to consider", "minimum": 1, "maximum": 20},
                        "index": {"type": "integer", "description": "Which matching result to save", "minimum": 0, "maximum": 19},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "add_todo_item",
                "description": "Add a task to the independent daily or weekly to-do list stored in data/todo.txt.",
                "parameters": {
                    "type": "object",
                    "required": ["text", "scope"],
                    "properties": {
                        "text": {"type": "string", "description": "Task text"},
                        "scope": {"type": "string", "enum": ["daily", "weekly"], "description": "Which to-do list to add to"},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "complete_todo_item",
                "description": "Mark a to-do item as done by id or text match.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "id": {"type": "string", "description": "Optional stable to-do item id"},
                        "text": {"type": "string", "description": "Optional text to match"},
                        "scope": {"type": "string", "enum": ["daily", "weekly"], "description": "Optional list scope filter"},
                    },
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "lookup_todo_items",
                "description": "Inspect the stored daily or weekly to-do list and reconcile it against the current day or current week calendar entries.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "scope": {"type": "string", "enum": ["daily", "weekly", "all"], "description": "Which list to inspect"},
                        "query": {"type": "string", "description": "Optional text filter"},
                        "done": {"type": "boolean", "description": "Optional done-state filter"},
                    },
                },
            },
        },
    ]

    messages: list[dict[str, Any]] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": transcript},
    ]

    calendar_changed = False
    focus_date: date | None = None
    saved_image_path: Path | None = None

    log("tool", "loop start", model=model_name, transcript=transcript)

    for _ in range(TOOL_LOOP_MAX_TURNS):
        log("tool", "ollama chat", turn=len(messages) - 2, message_count=len(messages))
        response = ollama.chat(
            model=model_name,
            messages=messages,
            tools=tool_schemas,
            options={"temperature": 0},
            stream=False,
        )

        response_data = response if isinstance(response, dict) else response.model_dump(exclude_none=True)
        message_dict = message_to_dict(response_data.get("message", {}))
        messages.append(message_dict)
        log("tool", "assistant message", content=preview_text(message_dict.get("content", "")), tool_calls=len(message_dict.get("tool_calls") or []))

        tool_calls = extract_tool_calls(message_dict)
        if not tool_calls:
            content = str(message_dict.get("content", "")).strip()
            log("tool", "loop complete", changed=calendar_changed, focus_date=focus_date, reply=content or "(empty)")
            return (content if content else "Done."), calendar_changed, focus_date, saved_image_path

        for tool_name, arguments in tool_calls:
            log("tool", "call", name=tool_name, arguments=json.dumps(arguments, sort_keys=True))
            if tool_name == "add_calendar_event":
                tool_result = tool_add_calendar_event(arguments)
                if tool_result.get("ok"):
                    calendar_changed = True
                    event = tool_result.get("event")
                    if isinstance(event, dict):
                        date_text = str(event.get("date", "")).strip()
                        try:
                            focus_date = datetime.strptime(date_text, "%Y-%m-%d").date()
                        except Exception:
                            focus_date = None
            elif tool_name == "remove_calendar_event":
                tool_result = tool_remove_calendar_event(arguments)
                if tool_result.get("ok"):
                    removed = tool_result.get("removed")
                    if isinstance(removed, list) and removed:
                        event = removed[0]
                        if isinstance(event, dict):
                            date_text = str(event.get("date", "")).strip()
                            try:
                                focus_date = datetime.strptime(date_text, "%Y-%m-%d").date()
                            except Exception:
                                focus_date = newest_event_after_removal()
                    if focus_date is None:
                        focus_date = newest_event_after_removal()
            elif tool_name == "lookup_calendar_events":
                tool_result = tool_lookup_calendar_events(arguments)
            elif tool_name == "lookup_save_image":
                tool_result = tool_lookup_save_image(arguments)
                if tool_result.get("ok"):
                    saved_path_text = str(tool_result.get("saved_path", "")).strip()
                    if saved_path_text:
                        saved_image_path = Path(saved_path_text)
            elif tool_name == "add_todo_item":
                tool_result = tool_add_todo_item(arguments)
            elif tool_name == "complete_todo_item":
                tool_result = tool_complete_todo_item(arguments)
            elif tool_name == "lookup_todo_items":
                tool_result = tool_lookup_todo_items(arguments)
            else:
                tool_result = {"ok": False, "error": f"unknown tool '{tool_name}'"}

            log("tool", "result", name=tool_name, result=json.dumps(tool_result, sort_keys=True))

            messages.append(
                {
                    "role": "tool",
                    "tool_name": tool_name,
                    "content": json.dumps(tool_result),
                }
            )

    log("tool", "loop limit reached")
    return "Reached tool loop limit.", calendar_changed, focus_date, saved_image_path


def month_events_for_render(current_year: int, current_month: int) -> list[dict[str, Any]]:
    events = load_calendar().get("events", [])
    output: list[dict[str, Any]] = []

    for event in events:
        try:
            event_date = datetime.strptime(event["date"], "%Y-%m-%d").date()
            event_time = validate_time_str(event["time"])
            recurrence = normalize_recurrence(event.get("recurrence"))
            title = str(event.get("title", "")).strip()
            if not title:
                continue

            if recurrence == "none":
                if event_date.year == current_year and event_date.month == current_month:
                    output.append(
                        {
                            "day": event_date.day,
                            "time": event_time,
                            "title": title,
                            "recurrence": recurrence,
                        }
                    )
            elif recurrence == "yearly":
                if event_date.month == current_month:
                    output.append(
                        {
                            "day": event_date.day,
                            "time": event_time,
                            "title": title,
                            "recurrence": recurrence,
                        }
                    )
        except Exception:
            continue

    output.sort(key=lambda e: (e["day"], e["time"], e["title"]))
    return output


def render_calendar_image(
    status_line: str,
    focus_year: int | None = None,
    focus_month: int | None = None,
    assistant_line: str = "",
) -> Image.Image:
    now = datetime.now()
    year = focus_year if focus_year is not None else now.year
    month = focus_month if focus_month is not None else now.month
    month_name = calendar_module.month_name[month]

    image = Image.new("RGB", (DISPLAY_WIDTH, DISPLAY_HEIGHT), (242, 244, 247))
    draw = ImageDraw.Draw(image)

    header_bg = (32, 72, 122)
    draw.rectangle((0, 0, DISPLAY_WIDTH - 1, 46), fill=header_bg)
    draw.text((10, 12), f"{month_name} {year}", fill=(255, 255, 255))
    draw.text((205, 12), "STAGE 4", fill=(255, 255, 255))

    weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    cell_width = DISPLAY_WIDTH // 7
    grid_top = 58
    row_height = 30

    for i, wd in enumerate(weekdays):
        draw.text((i * cell_width + 6, 48), wd, fill=(0, 0, 0))

    month_grid = calendar_module.monthcalendar(year, month)

    for row_idx, week in enumerate(month_grid):
        y0 = grid_top + row_idx * row_height
        y1 = y0 + row_height
        draw.line((0, y1, DISPLAY_WIDTH, y1), fill=(180, 180, 180), width=1)
        for col_idx, day_num in enumerate(week):
            x0 = col_idx * cell_width
            x1 = x0 + cell_width
            draw.line((x1, grid_top - row_height // 2, x1, grid_top + 6 * row_height), fill=(180, 180, 180), width=1)
            if day_num > 0:
                draw.text((x0 + 4, y0 + 4), str(day_num), fill=(0, 0, 0))

    events = month_events_for_render(year, month)
    days_with_events = {event["day"] for event in events}
    log("render", "calendar", month=f"{month_name} {year}", event_count=len(events), status=status_line, assistant=assistant_line)

    for row_idx, week in enumerate(month_grid):
        y0 = grid_top + row_idx * row_height
        for col_idx, day_num in enumerate(week):
            if day_num <= 0 or day_num not in days_with_events:
                continue
            x0 = col_idx * cell_width
            draw.ellipse((x0 + cell_width - 10, y0 + 4, x0 + cell_width - 4, y0 + 10), fill=(200, 40, 40))

    list_top = 258
    draw.rectangle((0, list_top - 2, DISPLAY_WIDTH - 1, DISPLAY_HEIGHT - 1), fill=(255, 255, 255))
    draw.text((8, list_top + 2), "Events", fill=(20, 20, 20))
    draw.rounded_rectangle((12, 214, 307, 250), radius=8, fill=(236, 242, 250), outline=(32, 72, 122), width=2)
    draw.text((22, 223), "HERMES", fill=(32, 72, 122))
    if assistant_line:
        draw.text((88, 223), assistant_line[:28], fill=(20, 20, 20))

    if events:
        for idx, event in enumerate(events[:8]):
            suffix = " (Y)" if event["recurrence"] == "yearly" else ""
            line = f"{event['day']:02d} {event['time']} {event['title']}{suffix}"
            draw.text((8, list_top + 20 + idx * 20), line[:46], fill=(40, 40, 40))
    else:
        draw.text((8, list_top + 24), "No events this month", fill=(90, 90, 90))

    draw.rectangle((0, DISPLAY_HEIGHT - 26, DISPLAY_WIDTH - 1, DISPLAY_HEIGHT - 1), fill=(230, 235, 241))
    draw.text((6, DISPLAY_HEIGHT - 20), status_line[:58], fill=(0, 0, 0))

    return image


def rgb888_to_rgb565_le_bytes(rgb_image: Image.Image) -> bytes:
    rgb = rgb_image.convert("RGB")
    output = bytearray(rgb.width * rgb.height * 2)
    index = 0

    for r, g, b in rgb.getdata():
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        output[index] = value & 0xFF
        output[index + 1] = (value >> 8) & 0xFF
        index += 2

    return bytes(output)


def build_img0_packet(image: Image.Image) -> bytes:
    if image.size != (DISPLAY_WIDTH, DISPLAY_HEIGHT):
        image = image.resize((DISPLAY_WIDTH, DISPLAY_HEIGHT), Image.Resampling.BILINEAR)

    payload = rgb888_to_rgb565_le_bytes(image)
    expected_len = DISPLAY_WIDTH * DISPLAY_HEIGHT * 2
    if len(payload) != expected_len:
        raise ValueError(f"bad payload length {len(payload)} (expected {expected_len})")

    header = struct.pack("<4sHHI", IMAGE_MAGIC, DISPLAY_WIDTH, DISPLAY_HEIGHT, len(payload))
    return header + payload


def send_pil_image_frame(sock: socket.socket, image: Image.Image, label: str = "image") -> None:
    if image.mode != "RGB":
        image = image.convert("RGB")
    if image.size != (DISPLAY_WIDTH, DISPLAY_HEIGHT):
        image = ImageOps.fit(image, (DISPLAY_WIDTH, DISPLAY_HEIGHT), method=Image.Resampling.LANCZOS)

    packet = build_img0_packet(image)
    sock.sendall(packet)
    log("img0", "sent", bytes=len(packet), width=DISPLAY_WIDTH, height=DISPLAY_HEIGHT, label=label)


def send_calendar_frame(
    sock: socket.socket,
    status_line: str,
    focus_year: int | None = None,
    focus_month: int | None = None,
    assistant_line: str = "",
) -> None:
    image = render_calendar_image(status_line, focus_year=focus_year, focus_month=focus_month, assistant_line=assistant_line)
    send_pil_image_frame(sock, image, label="calendar")


def send_image_file_frame(sock: socket.socket, image_path: Path) -> None:
    image = load_image_for_display(image_path)
    send_pil_image_frame(sock, image, label=image_path.name)


class WhisperTranscriber:
    def __init__(self) -> None:
        ensure_ffmpeg_on_path()
        log("whisper", "loading model", model=WHISPER_MODEL_NAME, device=WHISPER_DEVICE)
        self.model = whisper.load_model(WHISPER_MODEL_NAME, device=WHISPER_DEVICE)

    def transcribe(self, wav_path: Path) -> str:
        start_time = time.monotonic()
        log("whisper", "transcribe start", file=wav_path.name, bytes=wav_path.stat().st_size if wav_path.exists() else "missing")
        result = self.model.transcribe(str(wav_path), language="en", fp16=WHISPER_FP16)
        text = str(result.get("text", "")).strip()
        elapsed = time.monotonic() - start_time
        log("whisper", "transcribe done", seconds=f"{elapsed:.2f}s", chars=len(text), text=preview_text(text))
        return text


def process_utterance(conn: socket.socket, transcriber: WhisperTranscriber, wav_path: Path | None, model_name: str) -> None:
    if wav_path is None or not wav_path.exists():
        log("pipeline", "no recording captured")
        send_calendar_frame(conn, "No recording captured")
        return

    try:
        log("pipeline", "utterance ready", file=wav_path.name, bytes=wav_path.stat().st_size)
        transcript = transcriber.transcribe(wav_path)
        if not transcript:
            log("pipeline", "no speech detected")
            send_calendar_frame(conn, "No speech detected")
            return

        log("pipeline", "transcript", chars=len(transcript), text=transcript)
        log("pipeline", "calling hermes", model=model_name)
        assistant_reply, changed, focus_date, saved_image_path = run_tool_call_loop(transcript, model_name)
        log("pipeline", "hermes reply", changed=changed, focus_date=focus_date, image=saved_image_path, reply=assistant_reply)
        assistant_line = assistant_reply or "(no reply)"
        if saved_image_path is not None:
            log("pipeline", "render saved image", path=saved_image_path.name)
            send_image_file_frame(conn, saved_image_path)
            return
        if changed:
            status_line = f"Added event. {assistant_reply}"
        else:
            status_line = assistant_reply or "No calendar changes"
        if changed and focus_date is not None:
            log("pipeline", "render focused month", year=focus_date.year, month=focus_date.month)
            send_calendar_frame(conn, status_line, focus_year=focus_date.year, focus_month=focus_date.month, assistant_line=assistant_line)
        elif changed:
            latest_date = newest_calendar_event_date()
            if latest_date is not None:
                log("pipeline", "render latest event month", year=latest_date.year, month=latest_date.month)
                send_calendar_frame(conn, status_line, focus_year=latest_date.year, focus_month=latest_date.month, assistant_line=assistant_line)
            else:
                log("pipeline", "render current month after change")
                send_calendar_frame(conn, status_line, assistant_line=assistant_line)
        else:
            log("pipeline", "render current month without changes")
            send_calendar_frame(conn, status_line, assistant_line=assistant_line)
    except Exception as exc:
        log("pipeline", "error", error=exc)
        traceback.print_exc()
        send_calendar_frame(conn, f"Error: {exc}")


def main() -> None:
    ensure_runtime_dirs()

    model_name = ensure_ollama_model()
    log("boot", "using Ollama model", model=model_name)

    transcriber = WhisperTranscriber()

    log("boot", "listening", host=HOST, port=PORT)
    log("boot", "pipeline active")

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        server.bind((HOST, PORT))
        server.listen(1)

        while True:
            log("socket", "waiting for ESP32 connection")
            conn, addr = server.accept()
            log("socket", "connected", client=f"{addr[0]}:{addr[1]}")
            log("socket", "AUD0 stream ready")

            recording = RecordingState()

            with conn:
                while True:
                    try:
                        packet_type, payload = read_aud0_packet(conn)
                    except EOFError:
                        log("socket", "connection closed")
                        close_recording(recording)
                        break
                    except Exception as exc:
                        log("socket", "packet error", error=exc)
                        traceback.print_exc()
                        close_recording(recording)
                        break

                    if packet_type == PACKET_START:
                        log("packet", "start")
                        start_recording(recording)
                        continue

                    if packet_type == PACKET_AUDIO:
                        log("packet", "audio", bytes=len(payload), recording_bytes=recording.bytes_written + len(payload))
                        append_audio(recording, payload)
                        continue

                    if packet_type == PACKET_END:
                        log("packet", "end", recording_bytes=recording.bytes_written)
                        finished_path = close_recording(recording)
                        process_utterance(conn, transcriber, finished_path, model_name)
                        continue

                    log("packet", "unknown type", packet_type=packet_type, payload_bytes=len(payload))


if __name__ == "__main__":
    main()
